name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: (cargo install --vers "^0.4" mdbook)
      - run: mdbook build # && mdbook test
      - uses: JamesIves/github-pages-deploy-action@4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: book # The folder the action should deploy.